<?php

namespace App\Services\Automation;

use App\Models\AutomationRule;
use App\Models\Contact;
use App\Models\CrmActivity;
use App\Models\Lead;
use App\Models\Task;
use App\Models\User;
use Illuminate\Support\Facades\Log;

class AutomationService
{
    /**
     * Dispatch an event to matching active automation rules
     */
    public function handleTrigger(string $event, ?int $organizationId, array $context = []): void
    {
        if (!$organizationId) {
            return;
        }

        $rules = AutomationRule::where('organization_id', $organizationId)
            ->where('trigger_event', $event)
            ->where('is_active', true)
            ->get();

        foreach ($rules as $rule) {
            $this->executeRule($rule, $context);
        }
    }

    protected function executeRule(AutomationRule $rule, array $context): void
    {
        try {
            $actions = $rule->actions ?? [];
            foreach ($actions as $action) {
                $type = $action['type'] ?? '';

                switch ($type) {
                    case 'assign_agent':
                        $this->actionAssignAgent($rule->organization_id, $context, $action);
                        break;
                    case 'create_task':
                        $this->actionCreateTask($rule->organization_id, $context, $action);
                        break;
                    case 'update_contact_status':
                        $this->actionUpdateContactStatus($context, $action);
                        break;
                    case 'create_activity':
                        $this->actionCreateActivity($rule->organization_id, $context, $action);
                        break;
                    case 'log_notification':
                        Log::info("Automation Notification [{$rule->name}]", ['context' => $context, 'action' => $action]);
                        break;
                }
            }

            $rule->increment('execution_count');
            $rule->update(['last_triggered_at' => now()]);
        } catch (\Throwable $e) {
            Log::error("Automation execution error in rule [{$rule->id}]", ['error' => $e->getMessage()]);
        }
    }

    protected function actionAssignAgent(int $orgId, array $context, array $action): void
    {
        $lead = $context['lead'] ?? null;
        if (!($lead instanceof Lead)) return;

        $strategy = $action['strategy'] ?? 'round_robin';

        if ($strategy === 'round_robin') {
            $agents = User::where('organization_id', $orgId)
                ->whereIn('role', [User::ROLE_SALES_AGENT, User::ROLE_MANAGER])
                ->where('is_active', true)
                ->get();

            if ($agents->isNotEmpty()) {
                // Pick agent with fewest assigned active leads
                $selected = $agents->sortBy(fn($u) => $u->assignedLeads()->where('status', 'new')->count())->first();
                $lead->update(['assigned_user_id' => $selected->id]);
            }
        } elseif (!empty($action['user_id'])) {
            $lead->update(['assigned_user_id' => $action['user_id']]);
        }
    }

    protected function actionCreateTask(int $orgId, array $context, array $action): void
    {
        $lead = $context['lead'] ?? null;
        $contact = $context['contact'] ?? ($lead ? $lead->contact : null);

        Task::create([
            'organization_id' => $orgId,
            'assigned_user_id' => $lead ? $lead->assigned_user_id : null,
            'contact_id' => $contact ? $contact->id : null,
            'lead_id' => $lead ? $lead->id : null,
            'title' => $action['title'] ?? 'Automated Follow-up',
            'description' => $action['description'] ?? 'Generated by CRM automation workflow',
            'priority' => $action['priority'] ?? 'medium',
            'status' => 'pending',
            'due_date' => now()->addHours((int) ($action['due_hours'] ?? 24)),
        ]);
    }

    protected function actionUpdateContactStatus(array $context, array $action): void
    {
        $contact = $context['contact'] ?? null;
        if ($contact instanceof Contact && !empty($action['status'])) {
            $contact->update(['status' => $action['status']]);
        }
    }

    protected function actionCreateActivity(int $orgId, array $context, array $action): void
    {
        $contact = $context['contact'] ?? null;
        if ($contact instanceof Contact) {
            CrmActivity::create([
                'organization_id' => $orgId,
                'contact_id' => $contact->id,
                'type' => $action['activity_type'] ?? CrmActivity::TYPE_NOTE,
                'subject' => $action['subject'] ?? 'Automated Activity',
                'description' => $action['description'] ?? '',
                'occurred_at' => now(),
            ]);
        }
    }
}
